# Generated by Django 3.0.2 on 2020-01-02 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_order', '0002_auto_20200102_1951'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Customers',
        ),
    ]
