# Generated by Django 3.0.2 on 2020-01-02 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_order', '0004_auto_20200102_2005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
